"""empty message

Revision ID: 12dac917e131
Revises: 87a913c05775
Create Date: 2024-11-21 22:12:56.456661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12dac917e131'
down_revision = '87a913c05775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allergy_intolerance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'visits', ['visit_id'], ['id'])

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'visits', ['visit_id'], ['id'])

    with op.batch_alter_table('immunization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'visits', ['visit_id'], ['id'])

    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'visits', ['visit_id'], ['id'])

    with op.batch_alter_table('medication_statement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'visits', ['visit_id'], ['id'])

    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'visits', ['visit_id'], ['id'])

    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'visits', ['visit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visit_id')

    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visit_id')

    with op.batch_alter_table('medication_statement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visit_id')

    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visit_id')

    with op.batch_alter_table('immunization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visit_id')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visit_id')

    with op.batch_alter_table('allergy_intolerance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visit_id')

    # ### end Alembic commands ###
