"""empty message

Revision ID: 2bb61d57111a
Revises: dd1a1f0c6e3d
Create Date: 2025-01-14 11:10:58.366698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb61d57111a'
down_revision = 'dd1a1f0c6e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additionaldocument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additionaldocument', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###
