"""Initial migration.

Revision ID: 2f8115ba143e
Revises: 
Create Date: 2024-11-20 11:36:26.740353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8115ba143e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'doctor'), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('age', sa.String(length=10), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('id_card_number', sa.String(length=15), nullable=False),
    sa.Column('home_address', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('ecd_name', sa.String(length=50), nullable=True),
    sa.Column('ecd_contact_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('patient_basic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('age', sa.String(length=10), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('home_address', sa.String(length=100), nullable=False),
    sa.Column('ecd_name', sa.String(length=50), nullable=True),
    sa.Column('ecd_contact_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('user_education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('med_deg', sa.String(length=50), nullable=True),
    sa.Column('med_deg_spec', sa.String(length=50), nullable=True),
    sa.Column('board_cert', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_issuer', sa.String(length=50), nullable=True),
    sa.Column('license_expiration', sa.Date(), nullable=True),
    sa.Column('years_of_experience', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_education')
    op.drop_table('patient_basic')
    op.drop_table('users')
    # ### end Alembic commands ###
