"""empty message

Revision ID: 3c70af61a04e
Revises: 1c7a5ca48963
Create Date: 2024-11-18 12:38:19.396304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c70af61a04e'
down_revision = '1c7a5ca48963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecd_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ecd_contact_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('med_deg', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('med_deg_spec', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('board_cert', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('board_cert')
        batch_op.drop_column('med_deg_spec')
        batch_op.drop_column('med_deg')
        batch_op.drop_column('ecd_contact_number')
        batch_op.drop_column('ecd_name')

    # ### end Alembic commands ###
