"""updated visit class, form

Revision ID: 57364f8ea426
Revises: 9bb0ed75b190
Create Date: 2024-12-05 10:19:53.621259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57364f8ea426'
down_revision = '9bb0ed75b190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason_code', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('diagnosis_code', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=256), nullable=True))
        batch_op.alter_column('visit_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('visit_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('visit_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('location')
        batch_op.drop_column('status')
        batch_op.drop_column('diagnosis_code')
        batch_op.drop_column('reason_code')

    # ### end Alembic commands ###
