"""empty message

Revision ID: 61b946e0b5c9
Revises: 9b21dacdfcc3
Create Date: 2024-11-19 15:08:28.332247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61b946e0b5c9'
down_revision = '9b21dacdfcc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_education', schema=None) as batch_op:
        batch_op.alter_column('license_expiration',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_education', schema=None) as batch_op:
        batch_op.alter_column('license_expiration',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
