"""Initial Migration

Revision ID: 7e3986e27503
Revises: 
Create Date: 2024-11-21 17:31:01.534377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3986e27503'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_patient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('immunization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('vaccine_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('site', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_statement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('medication', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('effectivePeriod_start', sa.Date(), nullable=True),
    sa.Column('effectivePeriod_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('effectiveDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('performed_date', sa.Date(), nullable=True),
    sa.Column('performer_id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.Column('med_deg', sa.String(length=50), nullable=True),
    sa.Column('med_deg_spec', sa.String(length=50), nullable=True),
    sa.Column('board_cert', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_issuer', sa.String(length=50), nullable=True),
    sa.Column('license_expiration', sa.Date(), nullable=True),
    sa.Column('years_of_experience', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('date_recorded', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vitals')
    op.drop_table('user_education')
    op.drop_table('procedure')
    op.drop_table('observation')
    op.drop_table('medication_statement')
    op.drop_table('medical_history')
    op.drop_table('immunization')
    op.drop_table('doctor_patient')
    op.drop_table('appointment')
    # ### end Alembic commands ###
