"""empty message

Revision ID: 87a913c05775
Revises: f7fc339547f3
Create Date: 2024-11-21 21:48:52.859210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a913c05775'
down_revision = 'f7fc339547f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'visits', ['visit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visit_id')

    # ### end Alembic commands ###
