"""Revise Medication Statement

Revision ID: 9a90c2d39932
Revises: 06a437e5286b
Create Date: 2024-12-04 17:59:02.968709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a90c2d39932'
down_revision = '06a437e5286b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_statement', schema=None) as batch_op:
        batch_op.drop_column('dosage')
        batch_op.drop_column('medication')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_statement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('dosage', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
