"""empty message

Revision ID: 9b21dacdfcc3
Revises: 8781cd21f400
Create Date: 2024-11-19 13:13:38.489852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b21dacdfcc3'
down_revision = '8781cd21f400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_number', sa.String(length=50), nullable=False))
        batch_op.drop_column('license_num')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('license_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_number', mysql.VARCHAR(length=15), nullable=False))

    with op.batch_alter_table('user_education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_num', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('license_number')

    # ### end Alembic commands ###
