"""empty message

Revision ID: a4cc3956a431
Revises: f9370bb85849
Create Date: 2024-12-19 09:47:13.285981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4cc3956a431'
down_revision = 'f9370bb85849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allergy_intolerance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reaction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('onset', sa.Date(), nullable=True))

    with op.batch_alter_table('immunization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dose_quantity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=100), nullable=True))

    with op.batch_alter_table('medication_statement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication_code', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('dosage_instruction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('adherence', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reason_code', sa.Text(), nullable=True))
        batch_op.drop_column('medication')
        batch_op.drop_column('dosage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_statement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dosage', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('medication', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('reason_code')
        batch_op.drop_column('adherence')
        batch_op.drop_column('dosage_instruction')
        batch_op.drop_column('medication_code')

    with op.batch_alter_table('immunization', schema=None) as batch_op:
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('dose_quantity')
        batch_op.drop_column('route')

    with op.batch_alter_table('allergy_intolerance', schema=None) as batch_op:
        batch_op.drop_column('onset')
        batch_op.drop_column('reaction')
        batch_op.drop_column('category')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
