"""empty message

Revision ID: a88f745f89d4
Revises: 0c7de176cce9
Create Date: 2024-12-23 11:26:51.016724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88f745f89d4'
down_revision = '0c7de176cce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allergy_intolerance', schema=None) as batch_op:
        batch_op.alter_column('onset',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allergy_intolerance', schema=None) as batch_op:
        batch_op.alter_column('onset',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
