"""empty message

Revision ID: b5b2dcc54c67
Revises: c2718197789c
Create Date: 2025-01-13 23:37:33.499519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5b2dcc54c67'
down_revision = 'c2718197789c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additionaldocument', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('laboratoryscan', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratoryscan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('additionaldocument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
