"""empty message

Revision ID: c2718197789c
Revises: c6aba2a9468d
Create Date: 2025-01-13 23:10:47.323943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2718197789c'
down_revision = 'c6aba2a9468d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additionaldocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=150), nullable=False),
    sa.Column('document_file', sa.String(length=300), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratoryscan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('scan_name', sa.String(length=150), nullable=False),
    sa.Column('scan_file', sa.String(length=300), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laboratoryscan')
    op.drop_table('additionaldocument')
    # ### end Alembic commands ###
