"""Updated user model

Revision ID: c2e4900ac44b
Revises: c52355a9f145
Create Date: 2024-11-15 08:49:26.579805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2e4900ac44b'
down_revision = 'c52355a9f145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('id_card_number', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('license_number', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('home_address', sa.String(length=100), nullable=False))
        batch_op.drop_column('control_number')
        batch_op.drop_column('security_answer')
        batch_op.drop_column('street')
        batch_op.drop_column('phone')
        batch_op.drop_column('city')
        batch_op.drop_column('security_question')
        batch_op.drop_column('postal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('security_question', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('street', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('security_answer', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('control_number', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('home_address')
        batch_op.drop_column('license_number')
        batch_op.drop_column('id_card_number')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
