"""empty message

Revision ID: c52355a9f145
Revises: 65893052274e
Create Date: 2024-11-13 20:18:39.976304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c52355a9f145'
down_revision = '65893052274e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'user', 'doctor'),
               type_=sa.Enum('admin', 'patient', 'doctor'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'patient', 'doctor'),
               type_=mysql.ENUM('admin', 'user', 'doctor'),
               existing_nullable=False)

    # ### end Alembic commands ###
