"""empty message

Revision ID: c6aba2a9468d
Revises: 06a88ca466dd
Create Date: 2025-01-08 17:29:07.189772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6aba2a9468d'
down_revision = '06a88ca466dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.String(length=50), nullable=False))
        batch_op.alter_column('visit_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('clinical_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('verification_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('onset_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('abatement_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('notes',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('notes',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('abatement_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('onset_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('verification_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('clinical_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('visit_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
