"""empty message

Revision ID: dd1a1f0c6e3d
Revises: e4446315e0c9
Create Date: 2025-01-14 10:23:04.008117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd1a1f0c6e3d'
down_revision = 'e4446315e0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('lab_scans_ibfk_2', type_='foreignkey')
        batch_op.drop_column('patient_id')
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('patient_id', mysql.VARCHAR(length=50), nullable=False))
        batch_op.create_foreign_key('lab_scans_ibfk_2', 'patient_basic', ['patient_id'], ['id'])
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
