"""empty message

Revision ID: df9da53df1bb
Revises: e3a51e70f0d2
Create Date: 2024-12-22 21:09:24.396116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df9da53df1bb'
down_revision = 'e3a51e70f0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinical_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('abatement_date', sa.Date(), nullable=True))
        batch_op.drop_column('resolution_date')
        batch_op.drop_column('condition')

    with op.batch_alter_table('medication_statement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication_name', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('date_asserted', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('information_source', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reason_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('route_of_administration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('timing', sa.String(length=100), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reason_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('outcome', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('report', sa.Text(), nullable=True))
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('notes')

    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('effective_date', sa.DateTime(), nullable=False))
        batch_op.alter_column('value',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('type')
        batch_op.drop_column('date_recorded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_recorded', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('unit',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('value',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('effective_date')
        batch_op.drop_column('code')
        batch_op.drop_column('category')
        batch_op.drop_column('status')

    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', mysql.TEXT(), nullable=True))
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('report')
        batch_op.drop_column('outcome')
        batch_op.drop_column('reason_code')
        batch_op.drop_column('category')

    with op.batch_alter_table('medication_statement', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('timing')
        batch_op.drop_column('route_of_administration')
        batch_op.drop_column('category')
        batch_op.drop_column('notes')
        batch_op.drop_column('status_reason')
        batch_op.drop_column('reason_reference')
        batch_op.drop_column('information_source')
        batch_op.drop_column('date_asserted')
        batch_op.drop_column('medication_name')

    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('resolution_date', sa.DATE(), nullable=True))
        batch_op.drop_column('abatement_date')
        batch_op.drop_column('code')
        batch_op.drop_column('category')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('clinical_status')

    # ### end Alembic commands ###
