"""empty message

Revision ID: e3a51e70f0d2
Revises: a4cc3956a431
Create Date: 2024-12-22 19:38:35.082380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3a51e70f0d2'
down_revision = 'a4cc3956a431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('service_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('specialty', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('appointment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reason_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('participant_actor', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('participant_status', sa.String(length=20), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('participant_status')
        batch_op.drop_column('participant_actor')
        batch_op.drop_column('priority')
        batch_op.drop_column('reason_code')
        batch_op.drop_column('appointment_type')
        batch_op.drop_column('specialty')
        batch_op.drop_column('service_type')
        batch_op.drop_column('service_category')

    # ### end Alembic commands ###
