"""empty message

Revision ID: e4446315e0c9
Revises: b5b2dcc54c67
Create Date: 2025-01-14 10:00:01.963930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4446315e0c9'
down_revision = 'b5b2dcc54c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_scan_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['lab_scan_groups.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('laboratoryscan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratoryscan',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('scan_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('scan_file', mysql.VARCHAR(length=300), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_basic.id'], name='laboratoryscan_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('lab_scans')
    op.drop_table('lab_scan_groups')
    # ### end Alembic commands ###
