"""empty message

Revision ID: f9370bb85849
Revises: 57364f8ea426
Create Date: 2024-12-18 23:52:00.408695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9370bb85849'
down_revision = '57364f8ea426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_code', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('class_code')

    # ### end Alembic commands ###
