"""empty message

Revision ID: fef1c8c6aab6
Revises: 12dac917e131
Create Date: 2024-11-21 22:31:52.803127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fef1c8c6aab6'
down_revision = '12dac917e131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('visit_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('visit_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
